const express = require('express');
const router = express.Router();
const HomeController = require('./../app/controllers/HomeController');
const DashboardController = require('./../app/controllers/DashboardController');
router.get('/',HomeController.homeview);
router.get('/dashboard', DashboardController.dashboardView);
router.get('/login',HomeController.loginview);
router.post('/login',HomeController.checkLogin);
router.get('/apiPage',HomeController.apiView);
router.get('/signup',HomeController.signupView);
router.post('/signup',HomeController.signupAccount);
router.get('/signup_success',HomeController.signupSucessView);
module.exports = router;